# Generated by Django 4.2.2 on 2023-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "PENDING"),
                            ("Completed", "COMPLETED"),
                            ("In Progress", "IN_PROGRESS"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
